#!/bin/bash
set -ueo pipefail

# don't say anything you said earlier this week

if [[ ! "$QUESTTIME" -lt 604800 ]]; then
	# nice nice nice nice nice nice!
	sbin/transfer-balance "$BOTID" "$AUTHORID" 3500
	echo 'Your reward of $3500 has been awarded!'
	exit 101
fi

# no empty messages
if [ -z "$RAWMESSAGE" ] || [ -z "$MESSAGE" ]; then
	exit 0
fi

# commands may repeat.
if sbin/iscmd "$RAWMESSAGE" || sbin/iscmd "$MESSAGE"; then
	exit 0
fi

# Ignore "command-looking" messages.
# I'm just being nice.
if [ -n "$(cut -b 1 <<< "$MESSAGE" | grep -Ei -- "^(yui |[\-41\~\!\.?\$@])")" ]; then
	exit 0
fi

entry="$(printf '%s "%s"' "$(sbin/hashstr <<< "$RAWMESSAGE")" "$RAWMESSAGE")"
if [ -e "$QUESTHOME"/earlier-said ]; then
	if grep -Fxq -- "$entry" < "$QUESTHOME"/earlier-said; then
		exit 202
	fi
fi
printf '%s\n' "$entry" >> "$QUESTHOME"/earlier-said

exit 0

